[package]
name = "experiment"
version = "0.1.0"
edition = "2024"
authors = ["Adaickalavan <adaickalavan@gmail.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
image = "0.24"
viuer = "0.4"
mnist = "0.6.0"
ndarray = "0.16.1"
